[2025-02-19T10:24:53.130+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:53.149+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-02-19T10:24:53.161+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:53.166+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-02-19T10:24:53.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T10:24:53.179+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-02-19T10:24:53.180+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:53.191+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-02-19T10:24:53.191+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:53.192+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]>
[2025-02-19T10:24:53.192+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:53.192+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-02-19T10:24:53.200+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-02-19T10:24:53.203+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:53.203+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [queued]>
[2025-02-19T10:24:53.204+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-02-19T10:24:53.216+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): send_alert> on 2025-02-19 10:24:41.603923+00:00
[2025-02-19T10:24:53.223+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T10:24:53.225+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2025-02-19T10:24:53.225+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'send_alert', 'manual__2025-02-19T10:24:41.603923+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpv4fglgci']
[2025-02-19T10:24:53.226+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask send_alert
[2025-02-19T10:24:53.227+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7fce9a04a340>]
[2025-02-19T10:24:53.265+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:53.272+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [running]> on host d01efb841c31
[2025-02-19T10:24:53.272+0000] {settings.py:612} DEBUG - Disposing DB connection pool (PID 97)
[2025-02-19T10:24:53.273+0000] {settings.py:475} DEBUG - Setting up DB connection pool (PID 97)
[2025-02-19T10:24:53.273+0000] {settings.py:547} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-02-19T10:24:53.312+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:53.319+0000] {taskinstance.py:2383} DEBUG - Clearing XCom data
[2025-02-19T10:24:53.329+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-02-19T10:24:53.346+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-02-19T10:24:53.354+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='send_alert' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T10:24:41.603923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T10:24:41.603923+00:00'
[2025-02-19T10:24:53.354+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-02-19T10:24:53.356+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-02-19T10:24:53.356+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T10:24:53.356+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T10:24:53.356+0000] {logging_mixin.py:190} INFO - Current task name:send_alert state:running start_date:2025-02-19 10:24:53.192303+00:00
[2025-02-19T10:24:53.356+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2025-02-19T10:24:53.357+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-19T10:24:53.357+0000] {etl_pipeline.py:119} ERROR - Data validation failed. Alert sent!
[2025-02-19T10:24:53.357+0000] {etl_pipeline.py:120} ERROR - Data validation failed.
NoneType: None
[2025-02-19T10:24:53.358+0000] {python.py:240} INFO - Done. Returned value was: alert_sent
[2025-02-19T10:24:53.373+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-02-19T10:24:53.383+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-19T10:24:53.383+0000] {taskinstance.py:928} DEBUG - Clearing next_method and next_kwargs.
[2025-02-19T10:24:53.383+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=send_alert, run_id=manual__2025-02-19T10:24:41.603923+00:00, execution_date=20250219T102441, start_date=20250219T102453, end_date=20250219T102453
[2025-02-19T10:24:53.384+0000] {taskinstance.py:906} DEBUG - Task Duration set to 0.191501
[2025-02-19T10:24:53.394+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-19T10:24:53.394+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-19T10:24:53.395+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2025-02-19 10:24:41.626406+00:00
[2025-02-19T10:24:53.395+0000] {logging_mixin.py:190} INFO - Task hostname:d01efb841c31 operator:PythonOperator
[2025-02-19T10:24:53.395+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2025-02-19T10:24:53.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-19T10:24:53.457+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun etl_pipeline @ 2025-02-19 10:24:41.603923+00:00: manual__2025-02-19T10:24:41.603923+00:00, state:running, queued_at: 2025-02-19 10:24:41.626406+00:00. externally triggered: True>: 0 task(s)
[2025-02-19T10:24:53.457+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T10:24:53.459+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
